// src/content/douban/pages/user-profile/App.tsx
import { UmmPageLayout } from '@/content/douban/components/UmmPageLayout'
import { UmmImageWrapper } from '@/content/douban/components/UmmImageWrapper'
import { ASPECT_RATIO } from '@/content/douban/shared/constants'
import { EmptyState } from '@/shared/EmptyState'

interface PageProps { data: any }

export default function App({ data }: PageProps) {
  return (
    <UmmPageLayout type="movie">
      <div className="umm-page-root">
        <div className="umm-profile-header">
          <img src={data.avatarUrl} alt={data.displayName} className="umm-avatar umm-avatar--lg" />
          <div>
            <h1 className="umm-section-title">{data.displayName}</h1>
            {data.bio && <p className="umm-text">{data.bio}</p>}
          </div>
        </div>

        {data.sections?.map((sec: any, si: number) => (
          <div key={si} className="umm-section">
            <h2 className="umm-subsection-title">{sec.title}</h2>
            {sec.statLinks?.map((link: any, li: number) => (
              <a key={li} href={link.url} target="_blank" rel="noopener noreferrer" className="umm-link">{link.text}</a>
            ))}
            {sec.subsections?.map((sub: any, sui: number) => (
              <div key={sui} className="umm-grid">
                {sub.items.slice(0, 6).map((item: any, ii: number) => (
                  <a key={ii} href={item.url} target="_blank" rel="noopener noreferrer" className="umm-card">
                    <UmmImageWrapper src={item.posterUrl} alt={item.title} aspectRatio={ASPECT_RATIO.POSTER} />
                    <span className="umm-card-title">{item.title}</span>
                  </a>
                ))}
              </div>
            ))}
          </div>
        ))}

        {data.reviews?.length > 0 && (
          <div className="umm-section">
            <h2 className="umm-subsection-title">评论</h2>
            {data.reviews.slice(0, 5).map((r: any, i: number) => (
              <div key={i} className="umm-list-item">
                <span className="umm-list-item-title">{r.title}</span>
                <span className="umm-list-item-desc">{r.subjectTitle}</span>
                {r.excerpt && <p className="umm-text-sm">{r.excerpt}</p>}
              </div>
            ))}
          </div>
        )}

        {!data.sections?.length && !data.reviews?.length && <EmptyState />}
      </div>
    </UmmPageLayout>
  )
}

// src/scenario/douban/pages/movie-profile/App.vue
<script setup lang="ts">
import { UmmPageLayout } from '@/scenario/douban/components/umm-page-layout';
import UmmStatBar from '@/scenario/douban/components/UmmStatBar.vue';
import { t } from '../../shared/legacy-bridge';
import type { MovieProfileData } from './types';

defineProps<{
  data: MovieProfileData;
}>();
</script>

<template vapor>
  <UmmPageLayout type="movie">
    <div class="umm-movie-profile-root">
      <!-- Hero -->
      <div class="umm-hero">
        <div
          v-if="data.avatarUrl"
          class="umm-hero-avatar"
          :style="{ backgroundImage: `url(${data.avatarUrl})` }"
        />
        <div class="umm-hero-body">
          <h1 class="umm-hero-name">{{ data.displayName }}</h1>
        </div>
      </div>

      <!-- Stat Pills -->
      <UmmStatBar
        v-if="data.stats.length > 0"
        :items="data.stats.map((s) => ({ label: s.label, value: s.count, url: s.url }))"
      />

      <!-- Sections -->
      <div v-for="sec in data.sections" :key="sec.label" class="umm-dash-section">
        <div class="umm-dash-row-head">
          <span class="umm-dash-row-lbl">{{ sec.label }}</span>
          <a :href="sec.url" class="umm-dash-more" target="_blank">{{
            t('douban.mp.all_count', { count: sec.count.toLocaleString() })
          }}</a>
        </div>
        <div v-if="sec.items.length > 0" class="umm-dash-grid">
          <a
            v-for="item in sec.items"
            :key="item.url"
            :href="item.url"
            class="umm-dash-card"
            target="_blank"
          >
            <div
              class="umm-dash-card-cover"
              :style="{ backgroundImage: `url(${item.posterUrl})` }"
            />
            <span class="umm-dash-card-title">{{ item.title }}</span>
          </a>
        </div>
      </div>

      <!-- Celebrity & Review Row -->
      <UmmStatBar
        v-if="data.celebrityCount > 0 || data.reviewCount > 0"
        :items="[
          ...(data.celebrityCount > 0
            ? [
                {
                  label: t('douban.mp.celebrities'),
                  value: data.celebrityCount,
                  url: data.celebrityUrl,
                },
              ]
            : []),
          ...(data.reviewCount > 0
            ? [{ label: t('douban.mp.reviews'), value: data.reviewCount, url: data.reviewUrl }]
            : []),
        ]"
      />

      <!-- Doulists -->
      <div v-if="data.doulists.length > 0" class="umm-dash-section">
        <div class="umm-dash-row-head">
          <span class="umm-dash-row-lbl">{{ t('douban.mp.doulists') }}</span>
        </div>
        <div class="umm-movie-profile-doulist">
          <a
            v-for="dl in data.doulists"
            :key="dl.url"
            :href="dl.url"
            class="umm-movie-profile-doulist-item"
            target="_blank"
          >
            <span class="umm-movie-profile-doulist-title">{{ dl.title }}</span>
            <span class="umm-movie-profile-doulist-followers">{{
              t('douban.mp.followers', { count: dl.followers })
            }}</span>
          </a>
        </div>
      </div>
    </div>
  </UmmPageLayout>
</template>
