// src/components/ui/skeleton.tsx
import { cn } from "@/utils/cn"

function Skeleton({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn(
        "umm-animate-pulse umm-rounded-md umm-bg-primary/10",
        className
      )}
      {...props}
    />
  )
}

export { Skeleton }

// src/components/ui/skeleton/Skeleton.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/utils/cn"

interface SkeletonProps {
  class?: HTMLAttributes["class"]
}

const props = defineProps<SkeletonProps>()
</script>

<template>
  <div :class="cn('animate-pulse rounded-md bg-muted', props.class)" />
</template>
