// src/content/douban/pages/artists-overview/App.tsx
import { UmmPageLayout } from '@/content/douban/components/UmmPageLayout'
import { UmmImageWrapper } from '@/content/douban/components/UmmImageWrapper'
import { ASPECT_RATIO } from '@/content/douban/shared/constants'
import type { ArtistsOverviewData } from './types'

interface PageProps {
  data: ArtistsOverviewData
}

export default function App({ data }: PageProps) {
  return (
    <UmmPageLayout type="music">
      <div className="umm-page-root">
        <h2 className="umm-section-title">音乐人概览</h2>
        {data.genreNav.length > 0 && (
          <div className="umm-nav-bar">
            {data.genreNav.map((g: any, i: number) => (
              <a key={i} href={g.href} className="umm-nav-item">{g.name}</a>
            ))}
          </div>
        )}
        {data.recommendedArtists.length > 0 && (
          <div className="umm-section">
            <h3 className="umm-subsection-title">推荐音乐人</h3>
            <div className="umm-grid">
              {data.recommendedArtists.map((artist: any, i: number) => (
                <a key={i} href={artist.href} target="_blank" rel="noopener noreferrer" className="umm-card umm-card--sm">
                  <UmmImageWrapper src={artist.avatarUrl} alt={artist.name} aspectRatio={ASPECT_RATIO.SQUARE} />
                  <span className="umm-card-title">{artist.name}</span>
                </a>
              ))}
            </div>
          </div>
        )}
        {data.events.length > 0 && (
          <div className="umm-section">
            <h3 className="umm-subsection-title">演出活动</h3>
            <div className="umm-grid">
              {data.events.map((event: any, i: number) => (
                <a key={i} href={event.href} target="_blank" rel="noopener noreferrer" className="umm-card">
                  <UmmImageWrapper src={event.imageUrl} alt={event.title} aspectRatio={ASPECT_RATIO.WIDE} />
                  <span className="umm-card-title">{event.title}</span>
                  {event.description && <span className="umm-card-desc">{event.description}</span>}
                </a>
              ))}
            </div>
          </div>
        )}
        {data.videos.length > 0 && (
          <div className="umm-section">
            <h3 className="umm-subsection-title">视频</h3>
            <div className="umm-grid">
              {data.videos.map((video: any, i: number) => (
                <a key={i} href={video.href} target="_blank" rel="noopener noreferrer" className="umm-card">
                  <UmmImageWrapper src={video.imageUrl} alt={video.title} aspectRatio={ASPECT_RATIO.WIDE} />
                  <span className="umm-card-title">{video.title}</span>
                  {video.artistName && <span className="umm-card-desc">{video.artistName}</span>}
                </a>
              ))}
            </div>
          </div>
        )}
      </div>
    </UmmPageLayout>
  )
}

// apps/extension/src/content/douban/pages/artists-overview/App.vue
<script setup lang="ts">
import { UmmPageLayout } from '@/content/douban/components/UmmPageLayout'
import { UmmImageWrapper } from '@/content/douban/components/UmmImageWrapper'
import type { ArtistsOverviewData } from './types'

defineProps<{ data: ArtistsOverviewData }>()
</script>

<template>
  <UmmPageLayout type="music">
    <div class="umm-artists-root">
      <!-- Section: Recommended artists -->
      <div v-if="data.recommendedArtists.length > 0" class="umm-section">
        <h2 class="umm-section-title">你可能感兴趣的音乐人</h2>
        <div class="umm-artist-grid">
          <a
            v-for="(artist, i) in data.recommendedArtists"
            :key="i"
            :href="artist.href"
            target="_blank"
            rel="noopener noreferrer"
            class="umm-artist-card"
          >
            <div class="umm-artist-avatar">
              <UmmImageWrapper
                :src="artist.avatarUrl"
                :alt="artist.name"
                aspect-ratio="1"
              />
            </div>
            <span class="umm-artist-name">{{ artist.name }}</span>
          </a>
        </div>
      </div>

      <!-- Section: Events -->
      <div v-if="data.events.length > 0" class="umm-section">
        <h2 class="umm-section-title">推荐活动</h2>
        <div class="umm-event-list">
          <a
            v-for="(evt, i) in data.events"
            :key="i"
            :href="evt.href"
            target="_blank"
            rel="noopener noreferrer"
            class="umm-event-card"
          >
            <div class="umm-event-image">
              <UmmImageWrapper
                :src="evt.imageUrl"
                :alt="evt.title"
                aspect-ratio="1"
              />
            </div>
            <div class="umm-event-info">
              <div class="umm-event-desc">{{ evt.description }}</div>
            </div>
          </a>
        </div>
      </div>

      <!-- Section: Genre navigation -->
      <div v-if="data.genreNav.length > 0" class="umm-section">
        <h2 class="umm-section-title">流派</h2>
        <div class="umm-genre-section">
          <div class="umm-genre-tags">
            <a
              v-for="genre in data.genreNav"
              :key="genre.name"
              :href="genre.href"
              target="_blank"
              rel="noopener noreferrer"
              class="umm-genre-tag"
            >{{ genre.name }}</a>
          </div>
        </div>
      </div>
    </div>
  </UmmPageLayout>
</template>
