// src/components/ui/input.tsx
import * as React from "react"
import { cn } from "@/utils/cn"

const Input = React.forwardRef<
  HTMLInputElement,
  React.InputHTMLAttributes<HTMLInputElement>
>(({ className, type, ...props }, ref) => (
  <input
    type={type}
    className={cn(
      "umm-flex umm-h-9 umm-w-full umm-rounded-md umm-border umm-border-input umm-bg-transparent umm-px-3 umm-py-1 umm-text-sm umm-shadow-sm umm-transition-colors file:umm-border-0 file:umm-bg-transparent file:umm-text-sm file:umm-font-medium file:umm-text-foreground placeholder:umm-text-muted-foreground focus-visible:umm-outline-none focus-visible:umm-ring-1 focus-visible:umm-ring-ring disabled:umm-cursor-not-allowed disabled:umm-opacity-50",
      className
    )}
    ref={ref}
    {...props}
  />
))
Input.displayName = "Input"

export { Input }

// apps/extension/src/shared/ui/input/Input.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { useVModel } from '@vueuse/core'
import { cn } from '@/utils/cn'

const props = defineProps<{
  defaultValue?: string | number
  modelValue?: string | number
  class?: HTMLAttributes['class']
}>()

const emits = defineEmits<{
  (e: 'update:modelValue', payload: string | number): void
}>()

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <input
    v-model="modelValue"
    :class="cn('umm:flex umm:h-10 umm:w-full umm:rounded-md umm:border umm:border-input umm:bg-background umm:px-3 umm:py-2 umm:text-sm umm:ring-offset-background umm:file:border-0 umm:file:bg-transparent umm:file:text-sm umm:file:font-medium umm:placeholder:text-muted-foreground umm:focus-visible:outline-none umm:focus-visible:ring-2 umm:focus-visible:ring-ring umm:focus-visible:ring-offset-2 umm:disabled:cursor-not-allowed umm:disabled:opacity-50', props.class,
      )
"
  />
</template>
