// src/feature/ConfirmDialog.vue
<script setup lang="ts">
import { useConfirmStore } from '@/store/confirm';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/libraries/ui/dialog';
import { Button } from '@/libraries/ui/button';
import { Loader2 } from '@/libraries/ui/icons';

const confirmStore = useConfirmStore();
const { state } = confirmStore;
</script>

<template vapor>
  <Dialog
    :open="state.open"
    @update:open="
      (open: boolean) => {
        if (!open) state.open = false;
      }
    "
  >
    <DialogContent class="umm:sm:max-w-md">
      <DialogHeader>
        <DialogTitle class="umm:flex umm:items-center umm:gap-2">
          <component :is="state.icon" class="umm:h-5 umm:w-5 umm:text-primary" />
          {{ state.title }}
        </DialogTitle>
        <DialogDescription>{{ state.description }}</DialogDescription>
      </DialogHeader>

      <div
        v-if="state.warning"
        class="umm:rounded-lg umm:border umm:border-orange-200 umm:bg-orange-50 umm:p-3 umm:dark:border-orange-800 umm:dark:bg-orange-950"
      >
        <p class="umm:text-sm umm:text-orange-800 umm:dark:text-orange-200">{{ state.warning }}</p>
      </div>

      <div v-if="state.details" class="umm:text-sm umm:text-secondary-content">
        {{ state.details }}
      </div>

      <DialogFooter>
        <Button variant="outline" @click="state.open = false" :disabled="state.loading"
          >取消</Button
        >
        <Button @click="confirmStore.confirm" :disabled="state.loading" class="umm:gap-2">
          <Loader2 v-if="state.loading" class="umm:h-4 umm:w-4 umm:animate-spin" />
          {{ state.confirmText }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// src/shared/ConfirmDialog.tsx
import {
  Dialog, DialogContent, DialogDescription, DialogFooter,
  DialogHeader, DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { useConfirmStore } from "@/stores/use-confirm-store"

export function ConfirmDialog() {
  const { state, confirm } = useConfirmStore()
  const Icon = state.icon

  return (
    <Dialog open={state.open} onOpenChange={(open) => {
      if (!open && !state.loading) {
        useConfirmStore.setState({ state: { ...state, open: false } })
      }
    }}>
      <DialogContent className="sm:umm-max-w-md">
        <DialogHeader className="umm-flex umm-flex-row umm-items-center umm-gap-3">
          {Icon && <Icon className="umm-h-6 umm-w-6 umm-text-destructive" />}
          <div>
            <DialogTitle>{state.title}</DialogTitle>
            {state.description && (
              <DialogDescription>{state.description}</DialogDescription>
            )}
          </div>
        </DialogHeader>
        {state.warning && (
          <p className="umm-text-sm umm-text-amber-600 dark:umm-text-amber-400">{state.warning}</p>
        )}
        {state.details && (
          <p className="umm-text-sm umm-text-muted-foreground">{state.details}</p>
        )}
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => useConfirmStore.setState({ state: { ...state, open: false } })}
            disabled={state.loading}
          >
            取消
          </Button>
          <Button
            variant="default"
            onClick={confirm}
            disabled={state.loading}
          >
            {state.loading ? '处理中...' : (state.confirmText || '确认')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
