// src/components/ToastContainer.vue
<script setup lang="ts">
import { useToast } from '@/composables/useToast'
import { CheckCircle, XCircle, Info, Loader2, X } from 'lucide-vue-next'

const { toasts, dismiss } = useToast()

const icons = {
  success: CheckCircle,
  error: XCircle,
  info: Info,
  loading: Loader2,
}

const colors = {
  success: 'bg-green-500',
  error: 'bg-red-500',
  info: 'bg-blue-500',
  loading: 'bg-blue-500',
}
</script>

<template>
  <Teleport to="body">
    <div class="fixed bottom-6 right-6 z-[999999] flex flex-col gap-3 items-end pointer-events-none">
      <TransitionGroup
        enter-active-class="transition-all duration-300 ease-out"
        leave-active-class="transition-all duration-200 ease-in"
        enter-from-class="translate-x-full opacity-0"
        enter-to-class="translate-x-0 opacity-100"
        leave-from-class="translate-x-0 opacity-100"
        leave-to-class="translate-x-full opacity-0"
      >
        <div
          v-for="toast in toasts"
          :key="toast.id"
          :class="[
            'pointer-events-auto flex items-start gap-3 px-4 py-3 rounded-lg shadow-lg text-white min-w-[280px] max-w-[400px]',
            colors[toast.type],
          ]"
        >
          <component
            :is="icons[toast.type]"
            :class="['w-5 h-5 mt-0.5 shrink-0', toast.type === 'loading' && 'animate-spin']"
          />
          <div class="flex-1 min-w-0">
            <p class="font-medium text-sm">{{ toast.title }}</p>
            <p v-if="toast.message" class="text-xs opacity-90 mt-0.5">{{ toast.message }}</p>
          </div>
          <button
            @click="dismiss(toast.id)"
            class="shrink-0 p-0.5 rounded hover:bg-white/20 transition-colors"
          >
            <X class="w-4 h-4" />
          </button>
        </div>
      </TransitionGroup>
    </div>
  </Teleport>
</template>

// src/shared/ToastContainer.tsx
import { useEffect, useState } from "react"
import { cn } from "@/utils/cn"
import type { ToastType } from "@/shared/toast"
import { TOAST_AUTO_DISMISS_MS } from "@/shared/toast"

interface Toast {
  id: number
  type: ToastType
  title: string
  message?: string
}

interface ToastContainerProps {
  toasts: Toast[]
  onDismiss: (id: number) => void
  className?: string
}

const typeStyles: Record<ToastType, string> = {
  success: "umm-bg-green-50 umm-border-green-200 umm-text-green-800 dark:umm-bg-green-950 dark:umm-border-green-800 dark:umm-text-green-200",
  error: "umm-bg-red-50 umm-border-red-200 umm-text-red-800 dark:umm-bg-red-950 dark:umm-border-red-800 dark:umm-text-red-200",
  info: "umm-bg-blue-50 umm-border-blue-200 umm-text-blue-800 dark:umm-bg-blue-950 dark:umm-border-blue-800 dark:umm-text-blue-200",
  loading: "umm-bg-gray-50 umm-border-gray-200 umm-text-gray-800 dark:umm-bg-gray-950 dark:umm-border-gray-800 dark:umm-text-gray-200",
}

export function ToastContainer({ toasts, onDismiss, className }: ToastContainerProps) {
  if (toasts.length === 0) return null

  return (
    <div className={cn("umm-fixed umm-bottom-4 umm-right-4 umm-z-50 umm-flex umm-flex-col umm-gap-2", className)}>
      {toasts.map((toast) => (
        <ToastItem key={toast.id} toast={toast} onDismiss={onDismiss} />
      ))}
    </div>
  )
}

function ToastItem({ toast, onDismiss }: { toast: Toast; onDismiss: (id: number) => void }) {
  const [exiting, setExiting] = useState(false)

  useEffect(() => {
    if (toast.type !== 'loading') {
      const timer = setTimeout(() => {
        setExiting(true)
        setTimeout(() => onDismiss(toast.id), 300)
      }, TOAST_AUTO_DISMISS_MS)
      return () => clearTimeout(timer)
    }
  }, [toast, onDismiss])

  return (
    <div
      className={cn(
        "umm-rounded-lg umm-border umm-px-4 umm-py-3 umm-shadow-lg umm-transition-all umm-duration-300 umm-max-w-sm",
        typeStyles[toast.type],
        exiting ? "umm-opacity-0 umm-translate-x-4" : "umm-opacity-100 umm-translate-x-0"
      )}
    >
      <p className="umm-text-sm umm-font-medium">{toast.title}</p>
      {toast.message && <p className="umm-mt-1 umm-text-xs umm-opacity-80">{toast.message}</p>}
    </div>
  )
}
