// src/feature/ToastContainer.vue
<script setup lang="ts">
import { useToast } from '@/feature/composables/useToast'
import { CheckCircle, XCircle, Info, Loader2, X } from 'lucide-vue-next'

const { toasts, dismiss } = useToast()

const icons = {
  success: CheckCircle,
  error: XCircle,
  info: Info,
  loading: Loader2,
}

const colors = {
  success: 'umm:bg-state-success umm:text-state-success-on',
  error: 'umm:bg-state-error umm:text-state-error-on',
  info: 'umm:bg-state-info umm:text-state-info-on',
  loading: 'umm:bg-state-info umm:text-state-info-on',
}
</script>

<template>
  <Teleport to="body">
    <div class="umm:fixed umm:bottom-6 umm:right-6 umm:z-[999999] umm:flex umm:flex-col umm:gap-3 umm:items-end umm:pointer-events-none">
      <TransitionGroup
        enter-active-class="umm:transition-all umm:duration-300 umm:ease-out"
        leave-active-class="umm:transition-all umm:duration-200 umm:ease-in"
        enter-from-class="umm:translate-x-full umm:opacity-0"
        enter-to-class="umm:translate-x-0 umm:opacity-100"
        leave-from-class="umm:translate-x-0 umm:opacity-100"
        leave-to-class="umm:translate-x-full umm:opacity-0"
      >
        <div
          v-for="toast in toasts"
          :key="toast.id"
          :class="
  [
            'umm:pointer-events-auto umm:flex umm:items-start umm:gap-3 umm:px-4 umm:py-3 umm:rounded-lg umm:shadow-lg umm:min-w-[280px] umm:max-w-[400px]',
            colors[toast.type],
          ]
"
        >
          <component
            :is="icons[toast.type]"
            :class="
  ['umm:w-5 umm:h-5 umm:mt-0.5 umm:shrink-0', toast.type === 'loading' && 'umm:animate-spin']
"
          />
          <div class="umm:flex-1 umm:min-w-0">
            <p class="umm:font-medium umm:text-sm">{{ toast.title }}</p>
            <p v-if="toast.message" class="umm:text-xs umm:opacity-90 umm:mt-0.5">{{ toast.message }}</p>
          </div>
          <button
            @click="dismiss(toast.id)"
            class="umm:shrink-0 umm:p-0.5 umm:rounded umm:hover:bg-white/20 umm:transition-colors"
          >
            <X class="umm:w-4 umm:h-4" />
          </button>
        </div>
      </TransitionGroup>
    </div>
  </Teleport>
</template>

// src/shared/ToastContainer.tsx
import { useEffect, useState } from "react"
import { cn } from "@/utils/cn"
import type { ToastType } from "@/shared/toast"
import { TOAST_AUTO_DISMISS_MS } from "@/shared/toast"

interface Toast {
  id: number
  type: ToastType
  title: string
  message?: string
}

interface ToastContainerProps {
  toasts: Toast[]
  onDismiss: (id: number) => void
  className?: string
}

const typeStyles: Record<ToastType, string> = {
  success: "umm-bg-green-50 umm-border-green-200 umm-text-green-800 dark:umm-bg-green-950 dark:umm-border-green-800 dark:umm-text-green-200",
  error: "umm-bg-red-50 umm-border-red-200 umm-text-red-800 dark:umm-bg-red-950 dark:umm-border-red-800 dark:umm-text-red-200",
  info: "umm-bg-blue-50 umm-border-blue-200 umm-text-blue-800 dark:umm-bg-blue-950 dark:umm-border-blue-800 dark:umm-text-blue-200",
  loading: "umm-bg-gray-50 umm-border-gray-200 umm-text-gray-800 dark:umm-bg-gray-950 dark:umm-border-gray-800 dark:umm-text-gray-200",
}

export function ToastContainer({ toasts, onDismiss, className }: ToastContainerProps) {
  if (toasts.length === 0) return null

  return (
    <div className={cn("umm-fixed umm-bottom-4 umm-right-4 umm-z-50 umm-flex umm-flex-col umm-gap-2", className)}>
      {toasts.map((toast) => (
        <ToastItem key={toast.id} toast={toast} onDismiss={onDismiss} />
      ))}
    </div>
  )
}

function ToastItem({ toast, onDismiss }: { toast: Toast; onDismiss: (id: number) => void }) {
  const [exiting, setExiting] = useState(false)

  useEffect(() => {
    if (toast.type !== 'loading') {
      const timer = setTimeout(() => {
        setExiting(true)
        setTimeout(() => onDismiss(toast.id), 300)
      }, TOAST_AUTO_DISMISS_MS)
      return () => clearTimeout(timer)
    }
  }, [toast, onDismiss])

  return (
    <div
      className={cn(
        "umm-rounded-lg umm-border umm-px-4 umm-py-3 umm-shadow-lg umm-transition-all umm-duration-300 umm-max-w-sm",
        typeStyles[toast.type],
        exiting ? "umm-opacity-0 umm-translate-x-4" : "umm-opacity-100 umm-translate-x-0"
      )}
    >
      <p className="umm-text-sm umm-font-medium">{toast.title}</p>
      {toast.message && <p className="umm-mt-1 umm-text-xs umm-opacity-80">{toast.message}</p>}
    </div>
  )
}
