// src/entrypoints/options/tabs/SyncTab.tsx
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { WebDAVTab } from './sync/WebDAVTab'
import { ImportExportTab } from './sync/ImportExportTab'

export function SyncTab() {
  const { t } = useTranslation()
  const [activeSubTab, setActiveSubTab] = useState<'webdav' | 'import-export'>('webdav')

  return (
    <div className="umm:flex umm:flex-col umm:gap-[var(--umm-section-gap)]">
      <div className="umm:flex umm:gap-2">
        <Button
          variant={activeSubTab === 'webdav' ? 'default' : 'outline'}
          onClick={() => setActiveSubTab('webdav')}
        >
          WebDAV Sync
        </Button>
        <Button
          variant={activeSubTab === 'import-export' ? 'default' : 'outline'}
          onClick={() => setActiveSubTab('import-export')}
        >
          {t('tab.importExport')}
        </Button>
      </div>

      {activeSubTab === 'webdav' && <WebDAVTab />}
      {activeSubTab === 'import-export' && <ImportExportTab />}
    </div>
  )
}

// src/entrypoints/options/tabs/SyncTab.vue
<script setup lang="ts">
import { ref, defineAsyncComponent } from 'vue'
import { useI18n } from 'vue-i18n'
import SegmentedControl from '@/libraries/ui/segmented-control/SegmentedControl.vue'

const { t } = useI18n()
const activeSubTab = ref('webdav')

const WebDAVTab = defineAsyncComponent(() => import('./sync/WebDAVTab.vue'))
const ImportExportTab = defineAsyncComponent(() => import('./sync/ImportExportTab.vue'))

const subTabs = [
  { id: 'webdav', label: 'WebDAV' },
  { id: 'import-export', label: t('tab.importExport') as string },
]
</script>

<template>
  <div class="umm:flex umm:flex-col umm:gap-[var(--umm-section-gap)]">
    <SegmentedControl v-model="activeSubTab" :options="subTabs" />

    <Suspense>
      <WebDAVTab v-if="activeSubTab === 'webdav'" />
      <ImportExportTab v-else-if="activeSubTab === 'import-export'" />
      <template #fallback>
        <div class="umm:flex umm:flex-col umm:gap-4">
          <div class="umm:h-8 umm:bg-muted umm:rounded-lg umm:animate-pulse umm:w-1/3"></div>
          <div class="umm:h-4 umm:bg-muted umm:rounded-lg umm:animate-pulse umm:w-2/3"></div>
          <div class="umm:h-32 umm:bg-muted umm:rounded-xl umm:animate-pulse"></div>
        </div>
      </template>
    </Suspense>
  </div>
</template>
