// src/entrypoints/options/tabs/sync/WebDAVTab.tsx
import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { useToast } from '@/hooks/useToast'
import { useConfirmStore } from '@/stores/use-confirm-store'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Server, Upload, Download, RefreshCw, AlertCircle, CheckCircle2 } from 'lucide-react'
import { safeSendMessage } from '@/utils/context'

interface WebDAVConfig {
  url: string
  username: string
  password: string
}

export function WebDAVTab() {
  const { t } = useTranslation()
  const toast = useToast()
  const { show } = useConfirmStore()

  const [config, setConfig] = useState<WebDAVConfig>({ url: '', username: '', password: '' })
  const [isConfigSaved, setIsConfigSaved] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [isTesting, setIsTesting] = useState(false)
  const [loading, setLoading] = useState({ sync: false, download: false, upload: false })
  const [connectionStatus, setConnectionStatus] = useState<{
    type: 'success' | 'error' | 'idle'
    message?: string
  }>({ type: 'idle' })

  const isAnyRunning = Object.values(loading).some(Boolean) || isTesting || isSaving

  // Load config on mount
  useEffect(() => {
    async function loadConfig() {
      const result = await safeSendMessage<{ success: boolean; settings?: Record<string, any> }>(
        { type: 'GET_SETTINGS' },
        { timeout: 8000 }
      )
      if (result?.settings) {
        const s = result.settings
        setConfig({
          url: s.webdavUrl || '',
          username: s.webdavUsername || '',
          password: s.webdavPassword || '',
        })
        setIsConfigSaved(!!(s.webdavUrl && s.webdavUsername && s.webdavPassword))
      }
    }
    loadConfig()
  }, [])

  // Cross-tab sync via chrome.storage
  useEffect(() => {
    const onChange = (
      changes: Record<string, chrome.storage.StorageChange>,
      area: string
    ) => {
      if (area !== 'local') return
      const relevant = ['webdavUrl', 'webdavUsername', 'webdavPassword']
      if (!relevant.some((k) => k in changes)) return

      setConfig((prev) => ({
        url: (changes.webdavUrl?.newValue as string) ?? prev.url,
        username: (changes.webdavUsername?.newValue as string) ?? prev.username,
        password: (changes.webdavPassword?.newValue as string) ?? prev.password,
      }))
      const newUrl = (changes.webdavUrl?.newValue as string) ?? config.url
      const newUsername = (changes.webdavUsername?.newValue as string) ?? config.username
      const newPassword = (changes.webdavPassword?.newValue as string) ?? config.password
      setIsConfigSaved(!!(newUrl && newUsername && newPassword))
    }
    chrome.storage.onChanged.addListener(onChange)
    return () => {
      chrome.storage.onChanged.removeListener(onChange)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function updateConfig(field: keyof WebDAVConfig, value: string) {
    setConfig((prev) => ({ ...prev, [field]: value }))
    setIsConfigSaved(false)
  }

  async function saveConfig() {
    if (config.url && !config.url.startsWith('https://')) {
      toast.error(t('validation.httpsRequired') as string)
      return
    }

    setIsSaving(true)
    try {
      const result = await safeSendMessage<{ success: boolean }>(
        {
          type: 'UPDATE_SETTINGS',
          payload: {
            webdavUrl: config.url,
            webdavUsername: config.username,
            webdavPassword: config.password,
          },
        },
        { timeout: 8000 }
      )
      if (result?.success) {
        setIsConfigSaved(true)
        toast.success(t('toast.configSaved') as string)
      } else {
        throw new Error('Save failed')
      }
    } catch (e) {
      setIsConfigSaved(false)
      toast.error(t('toast.saveFailed') as string, String(e))
    } finally {
      setIsSaving(false)
    }
  }

  async function testConnection() {
    if (!config.url) {
      toast.error(t('validation.webdavUrlRequired') as string)
      return
    }
    if (!config.url.startsWith('https://')) {
      toast.error(t('validation.httpsRequired') as string)
      return
    }

    setIsTesting(true)
    setConnectionStatus({ type: 'idle' })
    try {
      const result = await safeSendMessage<{ success: boolean; message?: string }>(
        { type: 'WEBDAV_TEST', payload: config },
        { timeout: 10000 }
      )
      if (result?.success) {
        toast.success(t('toast.connectionSuccess') as string)
        setConnectionStatus({ type: 'success', message: t('toast.connectionSuccess') as string })
      } else {
        const errMsg = result?.message || t('toast.connectionFailed') as string
        toast.error(t('toast.connectionFailed') as string, errMsg)
        setConnectionStatus({ type: 'error', message: errMsg })
      }
    } catch (e) {
      const errMsg = String(e)
      toast.error(t('toast.connectionFailed') as string, errMsg)
      setConnectionStatus({ type: 'error', message: errMsg })
    } finally {
      setIsTesting(false)
    }
  }

  function syncCloud() {
    if (!isConfigSaved) {
      toast.error(t('validation.saveConfigFirst') as string)
      return
    }

    show({
      title: t('sync.smartMerge') as string,
      description: t('sync.smartMergeDesc') as string,
      icon: RefreshCw as any,
      confirmText: t('sync.startSync') as string,
      action: async () => {
        setLoading((prev) => ({ ...prev, sync: true }))
        try {
          const r = await safeSendMessage<{ success: boolean; message?: string }>(
            { type: 'WEBDAV_SYNC' },
            { timeout: 30000 }
          )
          if (r?.success) {
            toast.success(t('toast.syncSuccess') as string, r.message)
          } else {
            toast.error(t('toast.syncFailed') as string, r?.message)
          }
        } catch (e) {
          toast.error(t('toast.syncFailed') as string, String(e))
        } finally {
          setLoading((prev) => ({ ...prev, sync: false }))
        }
      },
    } as any)
  }

  function downloadCloud() {
    if (!isConfigSaved) {
      toast.error(t('validation.saveConfigFirst') as string)
      return
    }

    show({
      title: t('sync.cloudOverwrite') as string,
      description: t('sync.cloudOverwriteDesc') as string,
      icon: Download as any,
      confirmText: t('sync.confirmOverwrite') as string,
      action: async () => {
        setLoading((prev) => ({ ...prev, download: true }))
        try {
          const r = await safeSendMessage<{ success: boolean; message?: string }>(
            { type: 'WEBDAV_DOWNLOAD' },
            { timeout: 30000 }
          )
          if (r?.success) {
            toast.success(t('sync.downloadSuccess') as string, r.message)
          } else {
            toast.error(t('sync.downloadFailed') as string, r?.message)
          }
        } catch (e) {
          toast.error(t('sync.downloadFailed') as string, String(e))
        } finally {
          setLoading((prev) => ({ ...prev, download: false }))
        }
      },
    } as any)
  }

  function uploadCloud() {
    if (!isConfigSaved) {
      toast.error(t('validation.saveConfigFirst') as string)
      return
    }

    show({
      title: t('sync.localOverwrite') as string,
      description: t('sync.localOverwriteDesc') as string,
      icon: Upload as any,
      confirmText: t('sync.confirmOverwrite') as string,
      action: async () => {
        setLoading((prev) => ({ ...prev, upload: true }))
        try {
          const r = await safeSendMessage<{ success: boolean; message?: string }>(
            { type: 'WEBDAV_UPLOAD' },
            { timeout: 30000 }
          )
          if (r?.success) {
            toast.success(t('sync.uploadSuccess') as string, r.message)
          } else {
            toast.error(t('sync.uploadFailed') as string, r?.message)
          }
        } catch (e) {
          toast.error(t('sync.uploadFailed') as string, String(e))
        } finally {
          setLoading((prev) => ({ ...prev, upload: false }))
        }
      },
    } as any)
  }

  return (
    <div className="umm:flex umm:flex-col umm:gap-4">
      {/* WebDAV Configuration */}
      <Card>
        <CardHeader className="umm:pb-3">
          <div className="umm:flex umm:items-center umm:justify-between">
            <CardTitle className="umm:flex umm:items-center umm:gap-2">
              <Server className="umm:h-5 umm:w-5" />
              {t('settings.webdav')}
            </CardTitle>
            <span
              className={`umm:inline-flex umm:items-center umm:rounded-full umm:px-2.5 umm:py-0.5 umm:text-xs umm:font-medium ${
                isConfigSaved
                  ? 'umm:bg-green-100 umm:text-green-700 dark:umm:bg-green-900/30 dark:umm:text-green-400'
                  : 'umm:bg-orange-100 umm:text-orange-600 dark:umm:bg-orange-900/30 dark:umm:text-orange-400'
              }`}
            >
              {isConfigSaved ? t('toast.configSaved') : t('common.unsaved')}
            </span>
          </div>
        </CardHeader>
        <CardContent className="umm:flex umm:flex-col umm:gap-4">
          <div className="umm:grid umm:gap-2">
            <Label htmlFor="webdav-url">{t('common.serverUrl')}</Label>
            <Input
              id="webdav-url"
              value={config.url}
              onChange={(e) => updateConfig('url', e.target.value)}
              placeholder="https://example.com/dav/"
            />
          </div>
          <div className="umm:grid umm:gap-2">
            <Label htmlFor="webdav-username">{t('common.username')}</Label>
            <Input
              id="webdav-username"
              value={config.username}
              onChange={(e) => updateConfig('username', e.target.value)}
            />
          </div>
          <div className="umm:grid umm:gap-2">
            <Label htmlFor="webdav-password">{t('common.password')}</Label>
            <Input
              id="webdav-password"
              type="password"
              value={config.password}
              onChange={(e) => updateConfig('password', e.target.value)}
            />
          </div>

          <div className="umm:flex umm:gap-2">
            <Button onClick={saveConfig} disabled={isSaving || isAnyRunning} className="umm:flex-1">
              {isSaving ? (
                <>
                  <span className="umm:animate-spin umm:w-4 umm:h-4 umm-border-2 umm-border-current umm-border-t-transparent umm-rounded-full" />
                  {t('common.saving')}
                </>
              ) : (
                t('common.saveConfig')
              )}
            </Button>
            <Button
              onClick={testConnection}
              variant="outline"
              disabled={isTesting || isAnyRunning || !config.url}
              className="umm:flex-1"
            >
              {isTesting ? (
                <>
                  <span className="umm:animate-spin umm:w-4 umm:h-4 umm-border-2 umm-border-current umm-border-t-transparent umm-rounded-full" />
                  {t('common.testing')}
                </>
              ) : (
                t('common.testConnection')
              )}
            </Button>
          </div>

          {connectionStatus.type !== 'idle' && (
            <Alert variant={connectionStatus.type === 'error' ? 'destructive' : 'default'}>
              {connectionStatus.type === 'success' ? (
                <CheckCircle2 className="umm:h-4 umm:w-4" />
              ) : (
                <AlertCircle className="umm:h-4 umm:w-4" />
              )}
              <AlertTitle>
                {connectionStatus.type === 'success'
                  ? t('toast.connectionSuccess')
                  : t('toast.connectionFailed')}
              </AlertTitle>
              {connectionStatus.message && (
                <AlertDescription>{connectionStatus.message}</AlertDescription>
              )}
            </Alert>
          )}
        </CardContent>
      </Card>

      {/* Sync Operations */}
      <Card>
        <CardHeader className="umm:pb-3">
          <CardTitle className="umm:flex umm:items-center umm:gap-2">
            <RefreshCw className="umm:h-5 umm:w-5" />
            {t('sync.smartMerge')}
          </CardTitle>
        </CardHeader>
        <CardContent className="umm:flex umm:flex-col umm:gap-2">
          <Button
            variant="outline"
            className="umm:w-full"
            disabled={!isConfigSaved || isAnyRunning}
            onClick={downloadCloud}
          >
            {loading.download ? (
              <>
                <span className="umm:animate-spin umm:w-4 umm:h-4 umm-border-2 umm-border-current umm-border-t-transparent umm-rounded-full" />
                {t('common.downloading')}
              </>
            ) : (
              <>
                <Download className="umm:h-4 umm:w-4" />
                {t('sync.cloudOverwrite')}
              </>
            )}
          </Button>
          <Button
            variant="outline"
            className="umm:w-full"
            disabled={!isConfigSaved || isAnyRunning}
            onClick={uploadCloud}
          >
            {loading.upload ? (
              <>
                <span className="umm:animate-spin umm:w-4 umm:h-4 umm-border-2 umm-border-current umm-border-t-transparent umm-rounded-full" />
                {t('common.uploading')}
              </>
            ) : (
              <>
                <Upload className="umm:h-4 umm:w-4" />
                {t('sync.localOverwrite')}
              </>
            )}
          </Button>
          <Button
            className="umm:w-full"
            disabled={!isConfigSaved || isAnyRunning}
            onClick={syncCloud}
          >
            {loading.sync ? (
              <>
                <span className="umm:animate-spin umm:w-4 umm:h-4 umm-border-2 umm-border-current umm-border-t-transparent umm-rounded-full" />
                {t('common.syncing')}
              </>
            ) : (
              <>
                <RefreshCw className="umm:h-4 umm:w-4" />
                {t('sync.smartMerge')}
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}

// src/entrypoints/options/tabs/sync/WebDAVTab.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { Store } from '@/features/database'
import { STORAGE_KEYS } from '@/config'
import { safeSendMessage } from '@/utils/context'
import { useI18n } from 'vue-i18n'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { RefreshCw, Download, Upload } from 'lucide-vue-next'
import { useConfirmStore } from '@/stores/confirm'
import { useToast } from '@/composables/useToast'

const { t } = useI18n()
const toast = useToast()
const { show } = useConfirmStore()

const webdavConfig = ref({ url: '', username: '', password: '' })
const isConfigSaved = ref(false)
const loading = ref({ sync: false, download: false, upload: false })

const isAnyRunning = computed(() => Object.values(loading.value).some(v => v))

let webdavOnChangedUnsub: (() => void) | null = null

onMounted(async () => {
  const settings = await Store.getSettings()
  webdavConfig.value = { url: settings.webdavUrl || '', username: settings.webdavUsername || '', password: settings.webdavPassword || '' }
  isConfigSaved.value = !!(settings.webdavUrl && settings.webdavUsername && settings.webdavPassword)

  // Sync WebDAV config across tabs
  const onChange = (changes: Record<string, chrome.storage.StorageChange>, area: string) => {
    if (area !== 'local') return
    const relevant = [STORAGE_KEYS.WEBDAV_URL, STORAGE_KEYS.WEBDAV_USERNAME, STORAGE_KEYS.WEBDAV_PASSWORD]
    if (!relevant.some(k => k in changes)) return
    chrome.storage.local.get([STORAGE_KEYS.WEBDAV_URL, STORAGE_KEYS.WEBDAV_USERNAME, STORAGE_KEYS.WEBDAV_PASSWORD]).then(result => {
      webdavConfig.value = {
        url: (result[STORAGE_KEYS.WEBDAV_URL] as string) || '',
        username: (result[STORAGE_KEYS.WEBDAV_USERNAME] as string) || '',
        password: (result[STORAGE_KEYS.WEBDAV_PASSWORD] as string) || '',
      }
      isConfigSaved.value = !!(result[STORAGE_KEYS.WEBDAV_URL] && result[STORAGE_KEYS.WEBDAV_USERNAME] && result[STORAGE_KEYS.WEBDAV_PASSWORD])
    })
  }
  chrome.storage.onChanged.addListener(onChange)
  webdavOnChangedUnsub = () => { chrome.storage.onChanged.removeListener(onChange) }
})

onUnmounted(() => {
  webdavOnChangedUnsub?.()
})

async function saveConfig() {
  if (webdavConfig.value.url && !webdavConfig.value.url.startsWith('https://')) { toast.error(t('validation.httpsRequired')); return }
  try {
    await Store.updateSettings({ webdavUrl: webdavConfig.value.url, webdavUsername: webdavConfig.value.username, webdavPassword: webdavConfig.value.password })
    isConfigSaved.value = true
    toast.success(t('toast.configSaved'))
  } catch (e) { isConfigSaved.value = false; toast.error(t('toast.saveFailed'), String(e)) }
}

async function testConnection() {
  if (!webdavConfig.value.url) { toast.error(t('validation.webdavUrlRequired')); return }
  if (!webdavConfig.value.url.startsWith('https://')) { toast.error(t('validation.httpsRequired')); return }
  const result = await safeSendMessage({ type: 'WEBDAV_TEST', payload: webdavConfig.value }, { timeout: 10000 })
  if (result?.success) toast.success(t('toast.connectionSuccess')); else toast.error(t('toast.connectionFailed'), result?.message)
}

async function syncCloud() {
  if (!isConfigSaved.value) { toast.error(t('validation.saveConfigFirst')); return }
  show({
    title: t('sync.smartMerge'),
    description: t('sync.smartMergeDesc'),
    icon: RefreshCw,
    confirmText: t('sync.startSync'),
    action: async () => {
      loading.value.sync = true
      try {
        const r = await safeSendMessage({ type: 'WEBDAV_SYNC' }, { timeout: 30000 })
        if (r?.success) toast.success(t('toast.syncSuccess'), r.message)
        else toast.error(t('toast.syncFailed'), r?.message)
      } catch (e) { toast.error(t('toast.syncFailed'), String(e)) } finally { loading.value.sync = false }
    },
  })
}

async function downloadCloud() {
  if (!isConfigSaved.value) { toast.error(t('validation.saveConfigFirst')); return }
  show({
    title: t('sync.cloudOverwrite'),
    description: t('sync.cloudOverwriteDesc'),
    warning: t('sync.irreversible'),
    icon: Download,
    confirmText: t('sync.confirmOverwrite'),
    action: async () => {
      loading.value.download = true
      try {
        const r = await safeSendMessage({ type: 'WEBDAV_DOWNLOAD' }, { timeout: 30000 })
        if (r?.success) toast.success(t('sync.downloadSuccess'), r.message)
        else toast.error(t('sync.downloadFailed'), r?.message)
      } catch (e) { toast.error(t('sync.downloadFailed'), String(e)) } finally { loading.value.download = false }
    },
  })
}

async function uploadCloud() {
  if (!isConfigSaved.value) { toast.error(t('validation.saveConfigFirst')); return }
  show({
    title: t('sync.localOverwrite'),
    description: t('sync.localOverwriteDesc'),
    warning: t('sync.irreversible'),
    icon: Upload,
    confirmText: t('sync.confirmOverwrite'),
    action: async () => {
      loading.value.upload = true
      try {
        const r = await safeSendMessage({ type: 'WEBDAV_UPLOAD' }, { timeout: 30000 })
        if (r?.success) toast.success(t('sync.uploadSuccess'), r.message)
        else toast.error(t('sync.uploadFailed'), r?.message)
      } catch (e) { toast.error(t('sync.uploadFailed'), String(e)) } finally { loading.value.upload = false }
    },
  })
}
</script>

<template>
  <div class="space-y-[var(--section-gap)]">
    <div>
      <div class="flex items-center justify-between mb-4">
        <h3 class="font-h2 text-primary-content">{{ t('settings.webdav') }}</h3>
        <Badge v-if="isConfigSaved" variant="default" class="bg-green-500">{{ t('toast.configSaved') }}</Badge>
        <Badge v-else variant="outline" class="text-orange-500 border-orange-500">{{ t('common.unsaved') }}</Badge>
      </div>
      <div class="space-y-4">
        <div><Label>{{ t('common.serverUrl') }}</Label><Input v-model="webdavConfig.url" placeholder="https://example.com/dav/" class="mt-2" /></div>
        <div><Label>{{ t('common.username') }}</Label><Input v-model="webdavConfig.username" class="mt-2" /></div>
        <div><Label>{{ t('common.password') }}</Label><Input v-model="webdavConfig.password" type="password" class="mt-2" /></div>
        <div class="flex gap-2">
          <Button @click="saveConfig" class="flex-1">{{ t('common.saveConfig') }}</Button>
          <Button @click="testConnection" variant="outline" class="flex-1">{{ t('common.testConnection') }}</Button>
        </div>
      </div>
    </div>

    <Separator />

    <div>
      <h3 class="font-h2 text-primary-content mb-4">{{ t('sync.smartMerge') }}</h3>
      <div class="space-y-2">
        <Button @click="downloadCloud" variant="outline" class="w-full" :disabled="!isConfigSaved || isAnyRunning">
          <RefreshCw v-if="loading.download" class="mr-2 h-4 w-4 animate-spin" /><Download v-else class="mr-2 h-4 w-4" />
          {{ loading.download ? t('common.downloading') : t('sync.cloudOverwrite') }}
        </Button>
        <Button @click="uploadCloud" variant="outline" class="w-full" :disabled="!isConfigSaved || isAnyRunning">
          <RefreshCw v-if="loading.upload" class="mr-2 h-4 w-4 animate-spin" /><Upload v-else class="mr-2 h-4 w-4" />
          {{ loading.upload ? t('common.uploading') : t('sync.localOverwrite') }}
        </Button>
        <Button @click="syncCloud" class="w-full" :disabled="!isConfigSaved || isAnyRunning">
          <RefreshCw :class="['mr-2 h-4 w-4', loading.sync && 'animate-spin']" />
          {{ loading.sync ? t('common.syncing') : t('sync.smartMerge') }}
        </Button>
      </div>
    </div>
  </div>
</template>
