// src/scenario/douban/pages/homepage/components/UmmBillboardCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { UmmStatusBadgeWrapper } from '@/scenario/douban/components/UmmStatusBadgeWrapper'

interface Props {
  order: string
  title: string
  href: string
  badgeStatus: number
  badgeRating: number
  type?: 'movie' | 'music'
}

const props = defineProps<Props>()

const orderNum = computed(() => parseInt(props.order))
const rankClass = computed(() => {
  const n = orderNum.value
  if (n === 1) return 'umm-billboard-order--gold'
  if (n === 2) return 'umm-billboard-order--silver'
  if (n === 3) return 'umm-billboard-order--bronze'
  return ''
})
</script>

<template>
  <a :href="href" target="_blank" rel="noopener noreferrer" class="umm-billboard-card" :class="rankClass ? `umm-billboard-card--${orderNum === 1 ? 'gold' : orderNum === 2 ? 'silver' : 'bronze'}` : ''">
    <span class="umm-billboard-order" :class="rankClass">{{ order }}</span>
    <span class="umm-billboard-title">{{ title }}</span>
    <UmmStatusBadgeWrapper
      :status="badgeStatus"
      :rating="badgeRating"
      variant="small"
      :type="props.type ?? 'movie'"
    />
  </a>
</template>

// src/content/douban/pages/homepage/components/UmmBillboardCard.tsx
import React from 'react'
import { UmmStatusBadgeWrapper } from '@/content/douban/components/UmmStatusBadgeWrapper'

interface UmmBillboardCardProps {
  order: string
  title: string
  href: string
  badgeStatus: number
  badgeRating: number
  type?: 'movie' | 'music' | 'book' | 'game'
}

/**
 * UmmBillboardCard — ranking card for the weekly billboard section.
 * Shows rank number (with gold/silver/bronze styling for top 3),
 * title, and status badge.
 * Ported from the Vue UmmBillboardCard component.
 */
export const UmmBillboardCard: React.FC<UmmBillboardCardProps> = ({
  order,
  title,
  href,
  badgeStatus,
  badgeRating,
  type = 'movie',
}) => {
  const orderNum = parseInt(order, 10)
  const rankClass =
    orderNum === 1 ? 'umm-billboard-order--gold'
    : orderNum === 2 ? 'umm-billboard-order--silver'
    : orderNum === 3 ? 'umm-billboard-order--bronze'
    : ''

  const cardClass =
    orderNum === 1 ? 'umm-billboard-card--gold'
    : orderNum === 2 ? 'umm-billboard-card--silver'
    : orderNum === 3 ? 'umm-billboard-card--bronze'
    : ''

  return React.createElement(
    'a',
    {
      href,
      target: '_blank',
      rel: 'noopener noreferrer',
      className: `umm-billboard-card${cardClass ? ` ${cardClass}` : ''}`,
    },
    React.createElement('span', { className: `umm-billboard-order${rankClass ? ` ${rankClass}` : ''}` }, order),
    React.createElement('span', { className: 'umm-billboard-title' }, title),
    React.createElement(UmmStatusBadgeWrapper, {
      status: badgeStatus,
      rating: badgeRating,
      variant: 'small',
      type,
    }),
  )
}
