// src/content/douban/pages/doulists/App.vue
<script setup lang="ts">
import { UmmPageLayout } from '@/content/douban/components/UmmPageLayout'
import type { DoulistsPageData } from './types'

defineProps<{
  data: DoulistsPageData
}>()
</script>

<template>
  <UmmPageLayout type="movie">
    <div class="umm-doulists-root">
      <!-- User Bar -->
      <div v-if="data.displayName" class="umm-doulists-userbar">
        <div
          v-if="data.avatarUrl"
          class="umm-doulists-avatar"
          :style="{ backgroundImage: `url(${data.avatarUrl})` }"
        />
        <div class="umm-doulists-userinfo">
          <a :href="`/people/${data.userId}/`" class="umm-doulists-username" target="_blank">{{ data.displayName }}</a>
          <div v-if="data.navLinks.length > 0" class="umm-doulists-nav">
            <a
              v-for="link in data.navLinks"
              :key="link.url"
              :href="link.url"
              class="umm-doulists-navlink"
              target="_blank"
            >{{ link.label }}</a>
          </div>
        </div>
      </div>

      <!-- Tab Navigation -->
      <div v-if="data.createdUrl || data.collectedUrl" class="umm-doulists-tabs">
        <a
          v-if="data.createdUrl"
          :href="data.createdUrl"
          :class="['umm-doulist-tab', data.activeTab === 'created' ? 'umm-doulist-tab--active' : '']"
        >
          我创建的豆列
          <span class="umm-doulist-count">{{ data.createdCount }}</span>
        </a>
        <a
          v-if="data.collectedUrl"
          :href="data.collectedUrl"
          :class="['umm-doulist-tab', data.activeTab === 'collected' ? 'umm-doulist-tab--active' : '']"
        >
          我关注的豆列
          <span class="umm-doulist-count">{{ data.collectedCount }}</span>
        </a>
      </div>
      <div v-else class="umm-doulists-tabs">
        <span class="umm-doulist-tab umm-doulist-tab--active">
          我创建的豆列
          <span class="umm-doulist-count">{{ data.createdCount }}</span>
        </span>
      </div>

      <!-- List -->
      <div v-if="data.items.length > 0" class="umm-doulist-grid">
        <a
          v-for="item in data.items"
          :key="item.id"
          :href="item.url"
          class="umm-doulist-card"
          target="_blank"
        >
          <div v-if="item.coverUrl" class="umm-doulist-cover">
            <img :src="item.coverUrl" :alt="item.title" loading="lazy" />
          </div>
          <div class="umm-doulist-body">
            <h3 class="umm-doulist-title">{{ item.title }}</h3>
            <div class="umm-doulist-meta">
              <span>{{ item.itemCount }} 部</span>
              <span v-if="item.followerCount > 0"> · {{ item.followerCount }} 人关注</span>
            </div>
          </div>
        </a>
      </div>
      <div v-else class="umm-doulists-empty">暂无豆列</div>

      <!-- Paginator -->
      <div v-if="data.pageLinks.length > 0" class="umm-doulist-paginator">
        <a
          v-if="data.prevPageUrl"
          :href="data.prevPageUrl"
          class="umm-doulist-page"
        >‹</a>
        <a
          v-for="pl in data.pageLinks"
          :key="pl.label"
          :href="pl.url || undefined"
          :class="['umm-doulist-page', pl.current ? 'umm-doulist-page--active' : '']"
        >{{ pl.label }}</a>
        <a
          v-if="data.nextPageUrl"
          :href="data.nextPageUrl"
          class="umm-doulist-page"
        >›</a>
      </div>
    </div>
  </UmmPageLayout>
</template>

// src/content/douban/pages/movie-profile/App.tsx
import { UmmPageLayout } from '@/content/douban/components/UmmPageLayout'
import { UmmImageWrapper } from '@/content/douban/components/UmmImageWrapper'
import { ASPECT_RATIO } from '@/content/douban/shared/constants'
import { EmptyState } from '@/shared/EmptyState'


interface PageProps { data: any }

export default function App({ data }: PageProps) {
  return (
    <UmmPageLayout type="movie">
      <div className="umm-page-root">
        <div className="umm-profile-header">
          <img src={data.avatarUrl} alt={data.displayName} className="umm-avatar umm-avatar--lg" />
          <div>
            <h1 className="umm-section-title">{data.displayName}</h1>
            {data.stats && (
              <div className="umm-stats-row">
                {data.stats.map((s: any, i: number) => (
                  <a key={i} href={s.url} target="_blank" rel="noopener noreferrer" className="umm-stat-chip">
                    <span className="umm-stat-chip-count">{s.count}</span>
                    <span className="umm-stat-chip-label">{s.label}</span>
                  </a>
                ))}
              </div>
            )}
          </div>
        </div>

        {data.sections?.map((sec: any, si: number) => (
          <div key={si} className="umm-section">
            <h2 className="umm-subsection-title">{sec.label} ({sec.count})</h2>
            {sec.items.length > 0 ? (
              <div className="umm-grid">
                {sec.items.slice(0, 12).map((item: any, ii: number) => (
                  <a key={ii} href={item.url} target="_blank" rel="noopener noreferrer" className="umm-card">
                    <UmmImageWrapper src={item.posterUrl} alt={item.title} aspectRatio={ASPECT_RATIO.POSTER} />
                    <span className="umm-card-title">{item.title}</span>
                  </a>
                ))}
              </div>
            ) : <EmptyState title="暂无" />}
            {sec.count > 12 && (
              <a href={sec.url} target="_blank" rel="noopener noreferrer" className="umm-more-link">查看全部 {sec.count} 部</a>
            )}
          </div>
        ))}

        {data.doulists?.length > 0 && (
          <div className="umm-section">
            <h2 className="umm-subsection-title">我的豆列</h2>
            {data.doulists.map((d: any, i: number) => (
              <a key={i} href={d.url} target="_blank" rel="noopener noreferrer" className="umm-list-item">
                <span className="umm-list-item-title">{d.title}</span>
                <span className="umm-list-item-desc">{d.followers} 关注</span>
              </a>
            ))}
          </div>
        )}

        {!data.sections?.length && !data.doulists?.length && (
          <EmptyState title="暂无数据" />
        )}
      </div>
    </UmmPageLayout>
  )
}
