// src/scenario/douban/components/UmmUserBar.vue
<script setup lang="ts">
/**
 * UmmUserBar — shared user bar component for Douban user pages.
 *
 * Renders avatar + display name + navigation links row.
 * Uses var(--umm-*) CSS custom properties for Shadow DOM theme compatibility.
 * Appears when displayName is truthy.
 *
 * Props:
 * - avatarUrl: optional avatar URL (rendered as background-image on a circle)
 * - displayName: user's display name (linked to /people/{userId}/)
 * - userId: used for the display name link href
 * - navLinks: array of { label, url }
 */
defineProps<{
  avatarUrl?: string;
  displayName: string;
  userId: string;
  navLinks: { label: string; url: string }[];
}>();
</script>

<template vapor>
  <div v-if="displayName" class="umm-userbar">
    <div
      v-if="avatarUrl"
      class="umm-userbar-avatar"
      :style="{ backgroundImage: `url(${avatarUrl})` }"
    />
    <div class="umm-userbar-info">
      <a :href="`/people/${userId}/`" class="umm-userbar-name" target="_blank">{{ displayName }}</a>
      <div v-if="navLinks.length > 0" class="umm-userbar-nav">
        <a
          v-for="link in navLinks"
          :key="link.url"
          :href="link.url"
          class="umm-userbar-navlink"
          target="_blank"
          >{{ link.label }}</a
        >
      </div>
    </div>
  </div>
</template>

<style scoped>
/* ===== Shared User Bar — Shadow-DOM friendly ===== */
.umm-userbar {
  display: flex;
  align-items: center;
  gap: var(--umm-space-sm, 12px);
  margin-bottom: var(--umm-space-md, 16px);
  padding-bottom: var(--umm-space-sm, 10px);
  border-bottom: 1px solid var(--umm-border, #e3e8f0);
}
.umm-userbar-avatar {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background-size: cover;
  background-position: center;
  background-color: var(--umm-bg-secondary, #f1f4f9);
  flex-shrink: 0;
}
.umm-userbar-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}
.umm-userbar-name {
  font-size: var(--umm-font-sm, 0.85rem);
  font-weight: 600;
  color: var(--umm-text-primary, #151a23);
  text-decoration: none;
}
.umm-userbar-name:hover {
  color: var(--umm-link, #3a55ec);
}
.umm-userbar-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 2px 6px;
}
.umm-userbar-navlink {
  font-size: var(--umm-font-xs, 0.65rem);
  color: var(--umm-text-muted, #5d6a81);
  text-decoration: none;
  white-space: nowrap;
  padding: 1px 4px;
  border-radius: 4px;
  transition:
    color 0.15s,
    background 0.15s;
}
.umm-userbar-navlink:hover {
  color: var(--umm-link, #3a55ec);
  background: var(--umm-bg-secondary, #f1f4f9);
}
</style>

// src/content/douban/components/UmmUserBar.tsx
import React from 'react'

/**
 * UmmUserBar — shared user bar component for Douban user pages.
 *
 * Renders avatar + display name + navigation links row.
 * Uses var(--umm-*) CSS custom properties for Shadow DOM theme compatibility.
 * Appears when displayName is truthy.
 *
 * @prop avatarUrl   — optional avatar URL (rendered as background-image on a circle)
 * @prop displayName — user's display name (linked to /people/{userId}/)
 * @prop userId      — used for the display name link href
 * @prop navLinks    — array of { label, url }
 */

export interface NavLink {
  label: string
  url: string
}

export interface UmmUserBarProps {
  avatarUrl?: string
  displayName: string
  userId: string
  navLinks: NavLink[]
}

export function UmmUserBar({
  avatarUrl,
  displayName,
  userId,
  navLinks,
}: UmmUserBarProps): React.ReactElement | null {
  if (!displayName) return null

  return (
    <div className="umm-userbar">
      {avatarUrl && (
        <div
          className="umm-userbar-avatar"
          style={{ backgroundImage: `url(${avatarUrl})` }}
        />
      )}
      <div className="umm-userbar-info">
        <a
          href={`/people/${userId}/`}
          className="umm-userbar-name"
          target="_blank"
          rel="noopener noreferrer"
        >
          {displayName}
        </a>
        {navLinks.length > 0 && (
          <div className="umm-userbar-nav">
            {navLinks.map((link) => (
              <a
                key={link.url}
                href={link.url}
                className="umm-userbar-navlink"
                target="_blank"
                rel="noopener noreferrer"
              >
                {link.label}
              </a>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
