// src/libraries/ui/switch/Switch.vue
<script setup lang="ts">
import type { SwitchRootEmits, SwitchRootProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import {
  SwitchRoot,
  SwitchThumb,
  useForwardPropsEmits,
} from "reka-ui"
import { cn } from "@/libraries/utils/cn"

const props = defineProps<SwitchRootProps & { class?: HTMLAttributes["class"] }>()

const emits = defineEmits<SwitchRootEmits>()

const forwarded = useForwardPropsEmits(props, emits)
</script>

<template>
  <SwitchRoot
    v-bind="forwarded"
    :class="
  cn(
      'umm:peer umm:inline-flex umm:h-6 umm:w-11 umm:shrink-0 umm:cursor-pointer umm:items-center umm:rounded-full umm:border-2 umm:border-transparent umm:transition-colors umm:focus-visible:outline-none umm:focus-visible:ring-2 umm:focus-visible:ring-ring umm:focus-visible:ring-offset-2 umm:focus-visible:ring-offset-background umm:disabled:cursor-not-allowed umm:disabled:opacity-50 umm:data-[state=checked]:bg-primary umm:data-[state=unchecked]:bg-input',
      props.class,
    )
"
  >
    <SwitchThumb
      :class="
  cn('umm:pointer-events-none umm:block umm:h-5 umm:w-5 umm:rounded-full umm:bg-background umm:shadow-lg umm:ring-0 umm:transition-transform umm:data-[state=checked]:translate-x-5')
"
    >
      <slot name="thumb" />
    </SwitchThumb>
  </SwitchRoot>
</template>

// src/components/ui/switch.tsx
import * as React from "react"
import * as SwitchPrimitives from "@radix-ui/react-switch"
import { cn } from "@/utils/cn"

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      "umm-peer umm-inline-flex umm-h-5 umm-w-9 umm-shrink-0 umm-cursor-pointer umm-items-center umm-rounded-full umm-border-2 umm-border-transparent umm-shadow-sm umm-transition-colors focus-visible:umm-outline-none focus-visible:umm-ring-2 focus-visible:umm-ring-ring focus-visible:umm-ring-offset-2 focus-visible:umm-ring-offset-background disabled:umm-cursor-not-allowed disabled:umm-opacity-50 data-[state=checked]:umm-bg-primary data-[state=unchecked]:umm-bg-input",
      className
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        "umm-pointer-events-none umm-block umm-h-4 umm-w-4 umm-rounded-full umm-bg-background umm-shadow-lg umm-ring-0 umm-transition-transform data-[state=checked]:umm-translate-x-4 data-[state=unchecked]:umm-translate-x-0"
      )}
    />
  </SwitchPrimitives.Root>
))
Switch.displayName = SwitchPrimitives.Root.displayName

export { Switch }
